# Generated by Django 5.0 on 2024-11-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Azblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
